### ISSUE TITLE
ERROR on dumping config

### ISSUE THREAD

**Issue by 1311894932** [mingyuan-zhang/ReMoDiffuse#12]
Hello Dr.Zhang,  thanks for sharing code of great remodiffuse!

when I try to train remodiffuse:
./tools/dist_train.sh configs/remodiffuse/remodiffuse_t2m.py logs/remodiffuse/remodiffuse_t2m 1 --no-validate --gpu-ids 1
Or use this command:
PYTHONPATH=".":$PYTHONPATH python tools/train.py ${CONFIG_FILE} ${WORK_DIR} --no-validate

a weired error ocurred:
/home/zhouyang/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zhouyang/task_python/remodiffuse/tools/train.py", line 149, in <module>
    main()
  File "/home/zhouyang/task_python/remodiffuse/tools/train.py", line 99, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/zhouyang/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/home/zhouyang/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'

I have check the historical error, and i found this:
https://github.com/mingyuan-zhang/ReMoDiffuse/issues/3
it seems like still the dump function...

Any response will be appreciated !!!

**Comment by 1311894932** [comment]
https://blog.csdn.net/ZZZZ_Y_/article/details/133902230?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522169994987716800225578411%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=169994987716800225578411&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-133902230-null-null.142^v96^pc_search_result_base1&utm_term=FormatCode%28%29%20got%20an%20unexpected%20keyword%20argument%20verify&spm=1018.2226.3001.4187
