### ISSUE TITLE
Error on dumping config

### ISSUE THREAD

**Issue by non-void** [mingyuan-zhang/ReMoDiffuse#3]
Thanks for sharing code of your amazing work!!

I have encountered a problem when running your code. 

`python tools/train.py configs/remodiffuse/remodiffuse_t2m.py --work-dir mylogs --no-validate`

On line 99 of tools/train.py, we save the config using:

`cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))`

However, an exception comes:

> /home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf/pytree/pytree_utils.py", line 113, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 188, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 157, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 230, in addtoken
    return self._addtoken(ilabel, type, value, context)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 313, in _addtoken
    raise ParseError('bad input', type, value, context)
yapf_third_party._ylib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (165, 19))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 206, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf/pytree/pytree_utils.py", line 116, in ParseCodeToTree
    ast.parse(code)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 165
    **scale_func=<function scale_func at 0x7fb3d9765430>),**
               ^
SyntaxError: invalid syntax
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/panxiaoyu/anaconda3/envs/mogen/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 209, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:165:20: invalid syntax
python-BaseException

The issue is related to printing the scale_func to <function scale_func at 0x7fb3d9765430> and yapf treats it as an invalid syntax. How do you fix it? Or is it related to versions of installed librarys?

Thanks for your reply!!!

**Comment by mingyuan-zhang** [comment]
Sorry for the inconvenience. I update the config and model codes. Please pull the newest commit.
