### ISSUE TITLE
Can't train with multiple gpus using pytorch as launcher

### ISSUE THREAD

**Issue by Cr7st** [mingyuan-zhang/ReMoDiffuse#4]
Thanks for sharing the code! However I encountered some problem when trying to train with multiple gpus using pytorch as launcher.
```
PYTHONPATH=".":$PYTHONPATH python tools/train.py configs/remodiffuse/remodiffuse_t2m.py --work-dir testlogs --no-validate --gpu-ids 1 2 --launcher pytorch
```

I ran this command and got the following exception:
```
/home/zheng/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zheng/Code/ReMoDiffuse/tools/train.py", line 149, in <module>
    main()
  File "/home/zheng/Code/ReMoDiffuse/tools/train.py", line 92, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/zheng/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/runner/dist_utils.py", line 41, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/zheng/anaconda3/envs/mogen/lib/python3.9/site-packages/mmcv/runner/dist_utils.py", line 52, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/zheng/anaconda3/envs/mogen/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```

I checked `os.environ.keys()` and found that not only `RANK` was missing, but also `WORLD_SIZE`, `MASTER_ADDR` and `MASTER_PORT`. It seems that there is no new processes being spawned. I wonder if this code could train on multiple gpus with pytorch as launcher. Could you pls tell me how to do with pytorch?

Thank you!

**Comment by mingyuan-zhang** [comment]
Hi, I add a new script at `tools/dist_train.sh`, you can use pytorch launcher by the command below:
```shell
sh tools/dist_train.sh configs/remodiffuse/remodiffuse_kit.py logs/test2 2 --no-validate --gpu-ids 1 2
```
